name: Events (Activity Types)
on:
    push:
    pull_request: 
        types: [opened, reopened]
    issues: 
        types: [opened]
jobs: 
    checkout:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4
        