name: Expressions & Context 
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions and Context by @${{ github.actor}}, event: ${{ github.event_name }}"
jobs:
    issues_and_pull_request_job:
        runs-on: ubuntu-latest
        if: contains(fromJson('["issues, "pull_request"]'), github.event_name)
        steps:
            - name: Run only if issue has a bug label
              if: contains(github.event.issue.labels.*.name, 'bug')
              run: echo ${{ join(github.event.issue.labels.*.name, ', ') }}

    using_expressions_and_contexts:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Expressions 
              id: expressions 
              run: |
                echo ${{ 1}}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 'string' == 'String' }}
                echo ${{ 1 > 2 }}
                echo ${{ true || (false && true) }}
            - name: Dump Contexts
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(steps) }}'
                echo '${{ toJson(runner) }}'