name: Status Check Functions
on: [pull_request, push]
jobs:
    job_1: 
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: sleep 90
              timeout-minutes: 1
            - name: Step 2
              continue-on-error: true
              run: exit 1
            - name: Run on step 2 failure
              if: failure()
              run: echo 'Step 2 has failed'
            - if: success()
              run: echo "Run on success"
            - if: always()
              run: echo "Run on always"
            - if: cancelled()
              run: echo "Run on cancelled"

    job_2:
        runs-on: ubuntu-latest
        needs: job_1
        if: failure()
        steps:
            - run: echo 'Job 2'