name: Calling reusable workflows
on: 
    workflow_dispatch: 
        inputs:
            name: 
                description: "Input description"
                type: string 
                default: Sheilar 
                required: false 
jobs:
    calling-a-reusable-workflow: 
        uses: github-action-course-sheilar/workflows/.github/workflows/reusable.yaml@main
        with: 
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    calling-a-reuable-workflow-in-the-same-repo:
        uses: ./.github/workflows/reusable-workflow.yaml
    using-reusable-workflow-outputs:
        runs-on: ubuntu-latest
        needs: calling-a-reuable-workflow-in-the-same-repo
        steps:
            - run: echo ${{ needs.calling-a-reuable-workflow-in-the-same-repo.outputs.date }}