name: Variables & Secrets
on: [push]
jobs:
    logs-vars:
        runs-on: ${{ vars.JOB_RUNNER }}
        environment: 'staging'
        env: 
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
            ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
        steps:
            - name: Run only if BOOLEAN_SECRET is true
              if: env.BOOLEAN_SECRET == 'true'
              run: |
                echo "I ran because BOOLEAN_SECRET is true"
            - name: Log Vars
              run: |
                echo '${{ vars.JOB_RUNNER }}'
                echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
                echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
                echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"

