name: Workflow Run 
on: 
    workflow_run:
        workflows: [Events]
        types: [completed]
jobs:
    echo-string: 
        runs-on: ubuntu-latest
        steps:
            - run: echo "I was trigged because 'Events' workflow was completed."