name: Working Dirs and Shells
on: [push]
defaults:
    run:
        shell: bash
        #working-directory: /de/ed
jobs: 
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: | 
                pwd
                ls -a
                echo $GIHUB_SHA
                echo $GIHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Change Working Directory
              working-directory: /home/runner
              run: pwd
              
    display-wd-info-window:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display Working Directory & List Files
              run: | 
                Get-Location
                dir
                echo $env:GIHUB_SHA
                echo $env:GIHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
            - name: Python Shell
              shell: python
              run: |
                import platform
                print(platform.processor()) 
            